services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true

##### Listener
  austral.entity_file.configuration_checker.listener:
    class:          Austral\EntityFileBundle\Listener\ConfigurationCheckerListener
    arguments:      ["@austral.entity.mapping","@austral.entity_file.uploads.config", "@austral.entity_file.cropper.config"]
    tags:
      - { name: kernel.event_listener, event: "austral.event.admin.configuration_checker", method: configurationChecker }